<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1555337628702' stop='1555337628764'>
    <name>adding a new contact with an invalid phone number</name>
    <title>adding a new contact with an invalid phone number</title>
    <test-cases>
        <test-case start='1555337628702' status='failed' stop='1555337628734'>
            <name>should not create a new contact with a formatted telephone number</name>
            <title>should not create a new contact with a formatted telephone number</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: chrome not reachable
                  (Session info: chrome=72.0.3626.109)
                  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-46-generic x86_64)</message>
                <stack-trace>WebDriverError: chrome not reachable
                  (Session info: chrome=72.0.3626.109)
                  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-46-generic x86_64)
                    at Object.checkLegacyResponse (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
                    at parseHttpResponse (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
                    at doSend.then.response (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                From: Task: WebDriver.navigate().to(data:text/html,&lt;html>&lt;/html>)
                    at Driver.schedule (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
                    at Navigation.to (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1133:25)
                    at Driver.get (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:988:28)
                    at driver.controlFlow.execute.then.then (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/built/browser.js:675:32)
                    at ManagedPromise.invokeCallback_ (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
                    at TaskQueue.execute_ (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
                    at TaskQueue.executeNext_ (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
                    at asyncRun (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
                    at /home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
                From: Task: Run beforeEach in control flow
                    at UserContext.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasminewd2/index.js:94:19)
                    at attempt (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
                    at QueueRunner.run (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
                    at QueueRunner.execute (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:909:35)
                    at Spec.execute (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:526:10)
                    at UserContext.fn (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5340:37)
                    at attempt (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
                    at QueueRunner.run (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
                    at QueueRunner.execute (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4199:10)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/e2e/invalid-contact.e2e-spec.ts:35:5)
                    at addSpecsToSuite (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
                    at Env.describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
                    at describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
                    at Suite.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/e2e/invalid-contact.e2e-spec.ts:34:3)
                    at addSpecsToSuite (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
                    at Env.describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
                    at describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
                    at Object.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/e2e/invalid-contact.e2e-spec.ts:3:1)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1555337628734' status='failed' stop='1555337628764'>
            <name>should not create a new contact with too many numbers in the telephone number</name>
            <title>should not create a new contact with too many numbers in the telephone number</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: chrome not reachable
                  (Session info: chrome=72.0.3626.109)
                  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-46-generic x86_64)</message>
                <stack-trace>WebDriverError: chrome not reachable
                  (Session info: chrome=72.0.3626.109)
                  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-46-generic x86_64)
                    at Object.checkLegacyResponse (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
                    at parseHttpResponse (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
                    at doSend.then.response (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                From: Task: WebDriver.navigate().to(data:text/html,&lt;html>&lt;/html>)
                    at Driver.schedule (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
                    at Navigation.to (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1133:25)
                    at Driver.get (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:988:28)
                    at driver.controlFlow.execute.then.then (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/built/browser.js:675:32)
                    at ManagedPromise.invokeCallback_ (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
                    at TaskQueue.execute_ (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
                    at TaskQueue.executeNext_ (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
                    at asyncRun (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
                    at /home/jihene/Documents/GithubPFE/RunRepository-/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                From: Task: Run beforeEach in control flow
                    at UserContext.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasminewd2/index.js:94:19)
                    at attempt (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
                    at QueueRunner.run (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
                    at QueueRunner.execute (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:909:35)
                    at Spec.execute (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:526:10)
                    at UserContext.fn (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5340:37)
                    at attempt (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
                    at QueueRunner.run (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
                    at runNext (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/e2e/invalid-contact.e2e-spec.ts:35:5)
                    at addSpecsToSuite (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
                    at Env.describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
                    at describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
                    at Suite.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/e2e/invalid-contact.e2e-spec.ts:34:3)
                    at addSpecsToSuite (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
                    at Env.describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
                    at describe (/home/jihene/Documents/GithubPFE/RunRepository-/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
                    at Object.&lt;anonymous> (/home/jihene/Documents/GithubPFE/RunRepository-/e2e/invalid-contact.e2e-spec.ts:3:1)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>